import type { HttpContext } from '@adonisjs/core/http'; import { Kit,Telemetry,Alert,EnrichedTelemetry } from '../models/index.js'; import { emitLiveTelemetry } from '../services/socket_service.js'
const clean=(p:any)=>p||{}
export async function processTelemetry(id:string,p:any){const x=clean(p),kitId=x.kit_id||x.kitId||id; const doc=await Telemetry.create({kitId,deviceId:x.device_id||id,gpsCoordinates:{latitude:x.latitude??null,longitude:x.longitude??null},battery:{voltage_v:x.battery_voltage_v??null,current_a:x.battery_current_a??null,power_w:x.battery_power_w??null,state_of_charge_pct:x.state_of_charge_pct??null,state_of_health_pct:x.state_of_health_pct??null,error_code:x.battery_error_code??'NONE'},solar:x.solar||{},dc_load:x.dc_load||{},ac_load:x.ac_load||{},environment:x.environment||{},meta:x.meta||{},extraData:x}); await Kit.findOneAndUpdate({kitId},{$set:{gpsCoordinates:doc.gpsCoordinates,updatedAt:new Date()}},{upsert:true}); const enriched=await EnrichedTelemetry.create({...x,identity:{kit_id:kitId,device_id:id},records:[x]}); emitLiveTelemetry(kitId,enriched.toObject(),doc.toObject()); return x}
export async function processAlert(id:string,p:any){return Alert.create({kitId:id,source:p.source||'iot_esp32',type:p.type||'unknown_alert',severity:p.severity||'medium',label:p.label||'Alerte appareil',description:p.description||'Signal �mis par le mat�riel',metadata:p,status:'active'})}
export async function processStatus(id:string,status:any){return Kit.findOneAndUpdate({kitId:id},{$set:{status,updatedAt:new Date()}},{upsert:true})}
export async function receiveTelemetry({params,request,response}:HttpContext){const id=params.deviceId||request.input('deviceId')||request.input('device_id')||request.input('kit_id');if(!id)return response.badRequest({success:false,message:'deviceId et un payload JSON sont requis'});await processTelemetry(id,request.body());return response.accepted({success:true,message:'Telemetry accepted',deviceId:id})}
export async function receiveAlert({params,request,response}:HttpContext){const id=params.deviceId||request.input('deviceId');if(!id)return response.badRequest({success:false,message:'deviceId et un payload JSON sont requis'});await processAlert(id,request.body());return response.accepted({success:true,message:'Alert accepted',deviceId:id})}
export async function receiveStatus({params,request,response}:HttpContext){const id=params.deviceId||request.input('deviceId'),status=request.input('status');if(!id||!status)return response.badRequest({success:false,message:'deviceId et status sont requis'});await processStatus(id,status);return response.accepted({success:true,message:'Status accepted',deviceId:id})}
const queue:Record<string,any[]>={}; export async function commands({params,response}:HttpContext){const data=queue[params.deviceId]||[];queue[params.deviceId]=[];return response.ok({success:true,deviceId:params.deviceId,data})}
