import type { HttpContext } from '@adonisjs/core/http'; import axios from 'axios'; import {Client,Kit,Payment,ScoringData} from '../models/index.js'
const api=()=>axios.create({baseURL:process.env.ORANGE_ENERGY_API_URL||'https://orangeenergyapi.vercel.app',timeout:10000})
async function sync(path:string,model:any,filter?:any){try{const r=await api().get(path);for(const row of r.data?.data||[])await model.findOneAndUpdate(filter?filter(row):{kitId:row.kitId||row.paymentId||row.clientPhone},{$set:row},{upsert:true})}catch(e:any){console.error('[Orange Energy]',e.message)}return model.find().sort({createdAt:-1})}
export async function clients({response}:HttpContext){return response.ok({success:true,data:await Client.find().sort({createdAt:-1})})}
export async function kits({response}:HttpContext){return response.ok({success:true,data:await sync('/api/external/kits',Kit)})}
export async function kit({params,response}:HttpContext){try{const r=await api().get('/api/external/kits/'+encodeURIComponent(params.kitId));if(r.data?.data)await Kit.findOneAndUpdate({kitId:params.kitId},{$set:r.data.data},{upsert:true})}catch{}const x=await Kit.findOne({kitId:params.kitId});return x?response.ok({success:true,data:x}):response.notFound({success:false,message:'Kit not found'})}
export async function scoring({params,response}:HttpContext){if(!params.phone)return response.badRequest({success:false,message:'Phone parameter is required'});try{const r=await api().get('/api/external/scoring-data/'+encodeURIComponent(params.phone));if(r.data?.data)await ScoringData.findOneAndUpdate({clientPhone:params.phone},{$set:r.data.data},{upsert:true})}catch{}const x=await ScoringData.findOne({clientPhone:params.phone});return x?response.ok({success:true,data:x}):response.notFound({success:false,message:'Scoring data not found'})}
export async function payments({response}:HttpContext){return response.ok({success:true,data:await sync('/api/external/payments',Payment)})}
export async function paymentsByPhone({params,response}:HttpContext){return response.ok({success:true,data:await Payment.find({clientPhone:params.phone}).sort({date:-1})})}
