import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { AlertTriangle, Search, RefreshCw, ArrowUpRight, Bell, X } from 'lucide-react';
import { useAlertsQuery } from '../hooks/tanstack/useKitQueries';
import { asList, prioritize, formatDate, severityLabels, detailUrl } from '../lib/operations';
export default function FleetStatusFeed() {
  const query = useAlertsQuery();
  const [params, setParams] = useSearchParams();
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('open');
  const [selection, setSelection] = useState(null);
  const all = prioritize(asList(query.data));
  const selected = all.find(alert => alert._id === (selection || params.get('alertId')));
  const visible = all.filter(alert => {
    const open = alert.status === 'active' || alert.status === 'acknowledged';
    return (filter === 'all' || filter === 'open' && open || filter === 'critical' && open && ['critical','high'].includes(alert.severity) || filter === 'resolved' && alert.status === 'resolved') && [alert.kitId,alert.label,alert.description].join(' ').toLowerCase().includes(search.toLowerCase());
  });
  const statusLabel = {active:'À examiner',acknowledged:'Prise en compte',resolved:'Résolue'};
  return <div className="ops-page"><div className="ops-page-heading"><div><p className="ops-eyebrow">SURVEILLANCE DU PARC</p><h1>Centre d’alertes</h1><p>Des faits observés, une priorité explicite et un accès direct au diagnostic.</p></div><button className="ops-button" onClick={() => query.refetch()} disabled={query.isFetching}><RefreshCw size={15} className={query.isFetching ? 'ops-spin' : ''}/>Actualiser</button></div>
    <div className="ops-toolbar"><div className="ops-tabs" aria-label="Filtrer les alertes">{[['open','Ouvertes'],['critical','Prioritaires'],['resolved','Résolues'],['all','Toutes']].map(([key,label]) => <button key={key} aria-pressed={filter === key} className={filter === key ? 'active' : ''} onClick={() => setFilter(key)}>{label}</button>)}</div><label className="ops-input-wrap"><Search size={16}/><input aria-label="Rechercher une alerte" placeholder="Rechercher un kit, une anomalie…" value={search} onChange={event => setSearch(event.target.value)}/></label></div>
    {query.isError && <div role="alert" className="ops-notice"><AlertTriangle size={18}/>Impossible de charger les alertes. Aucune conclusion sur l’état du parc ne peut être tirée.<button onClick={() => query.refetch()}>Réessayer</button></div>}
    <div className={'ops-alert-layout ' + (selected ? 'has-detail' : '')}><section className="ops-card"><div className="ops-card-heading"><h2>{visible.length} alerte(s) affichée(s)</h2><small>100 dernières remontées</small></div>
      {query.isPending ? <p role="status" className="ops-empty">Chargement des alertes…</p> : visible.length === 0 ? <div className="ops-empty"><span className="ops-empty-icon"><Bell size={24}/></span><h3>{query.isError ? 'Source indisponible' : 'Aucune alerte dans cette vue'}</h3><p>Changez les filtres ou actualisez les données.</p></div> : <div className="ops-table-scroll"><table className="ops-table"><thead><tr><th>Priorité</th><th>Anomalie / équipement</th><th>État</th><th>Détection</th><th><span className="sr-only">Détails</span></th></tr></thead><tbody>{visible.map((alert,index) => <tr key={alert._id || index} className={selected === alert ? 'selected' : ''}><td><span className={'ops-badge ' + alert.severity}>{severityLabels[alert.severity] || 'Non classée'}</span></td><td><button className="ops-table-title" onClick={() => setSelection(alert._id)}>{alert.label || alert.type}</button><small>{alert.kitId || 'Équipement non identifié'}</small></td><td>{statusLabel[alert.status] || 'État inconnu'}</td><td>{formatDate(alert.createdAt)}</td><td><button className="ops-icon-button" aria-label={'Examiner ' + (alert.label || alert.type)} onClick={() => setSelection(alert._id)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>}
    </section>{selected && <aside className="ops-card ops-alert-detail"><div className="ops-card-heading"><h2>Détail de l’alerte</h2><button className="ops-icon-button" aria-label="Fermer le détail" onClick={() => {setSelection(null); setParams({}, {replace:true});}}><X size={18}/></button></div><div className="ops-detail-body"><span className={'ops-badge ' + selected.severity}>{severityLabels[selected.severity] || 'Non classée'}</span><h3>{selected.label || selected.type}</h3><p>{selected.description || 'Aucune description fournie.'}</p><dl><dt>Équipement</dt><dd>{selected.kitId || 'Non renseigné'}</dd><dt>Détection</dt><dd>{formatDate(selected.createdAt)}</dd><dt>Source</dt><dd>{{iot_esp32:'Capteur IoT',geofencing:'Géorepérage',system:'Système'}[selected.source] || selected.source || 'Non renseignée'}</dd><dt>Traitement</dt><dd>{statusLabel[selected.status] || 'Non renseigné'}</dd></dl>{selected.kitId && <><Link className="ops-button primary" to={detailUrl(selected.kitId,true)}>Examiner le diagnostic <ArrowUpRight size={15}/></Link><Link className="ops-button" to={'/InterventionWizard?kitId=' + encodeURIComponent(selected.kitId)}>Préparer une intervention</Link></>}<p className="ops-help">L’alerte est un signal à examiner. Confirmez la cause à partir des mesures et du contexte terrain.</p></div></aside>}</div>
  </div>;
}
